---
- name: Install requirements
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vimfiles_dependencies }}"

- name: Clone vimfiles
  become: yes
  become_user: "{{ vimfiles_user }}"
  git:
    repo: "{{ vimfiles_repo }}"
    dest: "~/.vim"
    version: master
    update: no

- name: "Install vimfiles for {{ vimfiles_user }}"
  become: yes
  become_user: "{{ vimfiles_user }}"
  command: /bin/bash install.sh
  args:
    chdir: "~/.vim/"
    creates: "~/.vimrc"

- debug:
    msg: "Start vim and run `:PluginInstall`"
